# Generated by Django 4.1.3 on 2022-12-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('idtipoactividad', models.SmallAutoField(db_column='IdTipoActividad', primary_key=True, serialize=False)),
                ('cvetipoactividad', models.CharField(db_column='CveTipoActividad', max_length=20)),
                ('desctipoactividad', models.CharField(db_column='DescTipoActividad', max_length=50)),
                ('bandactivo', models.BooleanField(blank=True, db_column='BandActivo', null=True)),
            ],
            options={
                'db_table': 'TIPO_ACTIVIDAD',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('idtipoevento', models.SmallAutoField(db_column='IdTipoEvento', primary_key=True, serialize=False)),
                ('cvetipoevento', models.CharField(db_column='CveTipoEvento', max_length=20)),
                ('desctipoevento', models.CharField(db_column='DescTipoEvento', max_length=50)),
                ('bandactivo', models.BooleanField(blank=True, db_column='BandActivo', null=True)),
            ],
            options={
                'db_table': 'TIPO_EVENTO',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('idtiposervicio', models.SmallAutoField(db_column='IdTipoServicio', primary_key=True, serialize=False)),
                ('cvetiposervicio', models.CharField(db_column='CveTipoServicio', max_length=20)),
                ('descservicio', models.CharField(db_column='DescServicio', max_length=50)),
                ('bandactivo', models.BooleanField(blank=True, db_column='BandActivo', null=True)),
            ],
            options={
                'db_table': 'TIPO_SERVICIO',
            },
        ),
        migrations.RemoveField(
            model_name='salon',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='Salon',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='TipoSalon',
        ),
    ]
