# Generated by Django 4.1.3 on 2023-02-24 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salones", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clasifservicio",
            old_name="descclasifservicio",
            new_name="descripcion",
        ),
        migrations.RenameField(
            model_name="desgloseservicio",
            old_name="descdesgloseservicio",
            new_name="descripcion",
        ),
        migrations.AlterField(
            model_name="clasifservicio",
            name="cvetiposervicio",
            field=models.ForeignKey(
                db_column="CveTipoServicio",
                on_delete=django.db.models.deletion.CASCADE,
                to="salones.tiposervicio",
            ),
        ),
        migrations.AlterField(
            model_name="desgloseservicio",
            name="cveclasifservicio",
            field=models.ForeignKey(
                db_column="CveClasifServicio",
                on_delete=django.db.models.deletion.CASCADE,
                to="salones.clasifservicio",
            ),
        ),
        migrations.AlterField(
            model_name="detevento",
            name="cveevento",
            field=models.ForeignKey(
                db_column="CveEvento",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="salones.encevento",
            ),
        ),
    ]
