# Generated by Django 4.1.3 on 2023-02-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="parametros_colores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elemento", models.CharField(db_column="elemento", max_length=50)),
                ("color", models.CharField(db_column="color", max_length=9)),
            ],
            options={
                "db_table": "parametros_colores",
            },
        ),
        migrations.CreateModel(
            name="parametros_imagenes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=60)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=200),
                ),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        height_field="height", upload_to="", width_field="width"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="encevento",
            name="opcion",
            field=models.PositiveSmallIntegerField(db_column="Opcion", default=1),
        ),
        migrations.AlterField(
            model_name="historicalencevento",
            name="opcion",
            field=models.PositiveSmallIntegerField(db_column="Opcion", default=1),
        ),
    ]
