# Generated by Django 4.1.3 on 2023-02-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salones", "0002_parametros_colores_parametros_imagenes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="encevento",
            old_name="folioevento",
            new_name="id_pk",
        ),
        migrations.RenameField(
            model_name="historicalencevento",
            old_name="folioevento",
            new_name="id_pk",
        ),
    ]
