# Generated by Django 4.1.3 on 2022-12-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0002_tipoactividad_tipoevento_tiposervicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactividad',
            name='bandactivo',
            field=models.BooleanField(blank=True, db_column='BandActivo', default=True, null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='cvetipoactividad',
            field=models.CharField(db_column='CveTipoActividad', max_length=20, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='desctipoactividad',
            field=models.CharField(db_column='DescTipoActividad', max_length=50, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='bandactivo',
            field=models.BooleanField(blank=True, db_column='BandActivo', default=True, null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='cvetipoevento',
            field=models.CharField(db_column='CveTipoEvento', help_text='La clave que se mostrara en menus', max_length=20, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='desctipoevento',
            field=models.CharField(db_column='DescTipoEvento', max_length=50, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='bandactivo',
            field=models.BooleanField(blank=True, db_column='BandActivo', default=True, null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='cvetiposervicio',
            field=models.CharField(db_column='CveTipoServicio', max_length=20, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='descservicio',
            field=models.CharField(db_column='DescServicio', max_length=50, verbose_name='Descripcion'),
        ),
    ]
