# Generated by Django 4.1.3 on 2022-12-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0002_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactividad',
            name='clave',
            field=models.CharField(db_column='CveTipoActividad', max_length=20, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='clave',
            field=models.CharField(db_column='CveTipoEvento', help_text='La clave que se mostrara en menus', max_length=20, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='clave',
            field=models.CharField(db_column='CveTipoServicio', max_length=20, unique=True, verbose_name='Clave'),
        ),
    ]
