# Generated by Django 4.1.3 on 2023-02-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salones", "0003_rename_folioevento_encevento_id_pk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalenceventoopcion",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="detevento",
            name="cveopcion",
        ),
        migrations.RemoveField(
            model_name="historicaldetevento",
            name="cveopcion",
        ),
        migrations.AddField(
            model_name="detevento",
            name="cveevento",
            field=models.ForeignKey(
                db_column="CveEvento",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="salones.encevento",
            ),
        ),
        migrations.AddField(
            model_name="encevento",
            name="numeropersonas",
            field=models.PositiveSmallIntegerField(
                db_column="numero_personas", default=0, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldetevento",
            name="cveevento",
            field=models.ForeignKey(
                blank=True,
                db_column="CveEvento",
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="salones.encevento",
            ),
        ),
        migrations.AddField(
            model_name="historicalencevento",
            name="numeropersonas",
            field=models.PositiveSmallIntegerField(
                db_column="numero_personas", default=0, null=True
            ),
        ),
        migrations.AlterField(
            model_name="encevento",
            name="opcion",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3")], db_column="Opcion", default=1
            ),
        ),
        migrations.AlterField(
            model_name="historicalencevento",
            name="opcion",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3")], db_column="Opcion", default=1
            ),
        ),
        migrations.DeleteModel(
            name="EncEventoOpcion",
        ),
        migrations.DeleteModel(
            name="HistoricalEncEventoOpcion",
        ),
    ]
