# Generated by Django 4.1.3 on 2022-12-20 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salones', '0003_alter_tipoactividad_clave_alter_tipoevento_clave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTipoServicio',
            fields=[
                ('id_pk', models.IntegerField(blank=True, db_column='IdTipoServicio', db_index=True)),
                ('clave', models.CharField(db_column='CveTipoServicio', db_index=True, max_length=20, verbose_name='Clave')),
                ('descripcion', models.CharField(db_column='DescServicio', max_length=50, verbose_name='Descripcion')),
                ('bandactivo', models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tipo servicio',
                'verbose_name_plural': 'historical tipo servicios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTipoEvento',
            fields=[
                ('id_pk', models.IntegerField(blank=True, db_column='IdTipoEvento', db_index=True)),
                ('clave', models.CharField(db_column='CveTipoEvento', db_index=True, help_text='La clave que se mostrara en menus', max_length=20, verbose_name='Clave')),
                ('descripcion', models.CharField(db_column='DescTipoEvento', max_length=50, verbose_name='Descripcion')),
                ('bandactivo', models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tipo evento',
                'verbose_name_plural': 'historical tipo eventos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTipoActividad',
            fields=[
                ('id_pk', models.IntegerField(blank=True, db_column='IdTipoActividad', db_index=True)),
                ('clave', models.CharField(db_column='CveTipoActividad', db_index=True, max_length=20, verbose_name='Clave')),
                ('descripcion', models.CharField(db_column='DescTipoActividad', max_length=50, verbose_name='Descripcion')),
                ('bandactivo', models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tipo actividad',
                'verbose_name_plural': 'historical tipo actividads',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFoto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('image', models.TextField(max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Foto',
                'verbose_name_plural': 'historical Fotos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
