# Generated by Django 4.1.3 on 2022-12-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0005_clasifservicio_desgloseservicio_detevento_encevento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltipoevento',
            name='descripcion',
            field=models.CharField(db_column='DescTipoEvento', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='descripcion',
            field=models.CharField(db_column='DescTipoEvento', max_length=50),
        ),
    ]
