# Generated by Django 4.1.3 on 2023-02-13 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salones", "0006_alter_detevento_iddetalle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detevento",
            name="proveedor",
            field=models.ForeignKey(
                db_column="cveproveedor",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="salones.personaprincipal",
                verbose_name="Proveedor",
            ),
        ),
        migrations.AddField(
            model_name="historicaldetevento",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                db_column="cveproveedor",
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="salones.personaprincipal",
                verbose_name="Proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="detevento",
            name="nota",
            field=models.CharField(
                blank=True,
                db_column="Notas",
                default=None,
                max_length=100,
                null=True,
                verbose_name="Notas",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldetevento",
            name="nota",
            field=models.CharField(
                blank=True,
                db_column="Notas",
                default=None,
                max_length=100,
                null=True,
                verbose_name="Notas",
            ),
        ),
    ]
