# Generated by Django 4.1.3 on 2023-01-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0006_alter_historicaltipoevento_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desgloseservicio',
            name='cvetiposervicio',
        ),
        migrations.RemoveField(
            model_name='historicaldesgloseservicio',
            name='cvetiposervicio',
        ),
        migrations.AlterField(
            model_name='clasifservicio',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='desgloseservicio',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='encevento',
            name='banaprovada',
            field=models.BooleanField(db_column='BanAprovada', default=True, verbose_name='Aprobada'),
        ),
        migrations.AlterField(
            model_name='estatusactividad',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='fasesprocesos',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='historicalclasifservicio',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='historicaldesgloseservicio',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='historicalencevento',
            name='banaprovada',
            field=models.BooleanField(db_column='BanAprovada', default=True, verbose_name='Aprobada'),
        ),
        migrations.AlterField(
            model_name='historicalestatusactividad',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='historicalfasesprocesos',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='historicalpersonaprincipal',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='historicalprocesos',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='historicaltipoactividad',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='historicaltipoevento',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='historicaltipopersona',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='personaprincipal',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipopersona',
            name='bandactivo',
            field=models.BooleanField(db_column='BandActivo', default=True, verbose_name='Activo'),
        ),
    ]
