# Generated by Django 4.1.3 on 2023-01-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0007_remove_desgloseservicio_cvetiposervicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldesgloseservicio',
            name='cveclasifservicio',
        ),
        migrations.RemoveField(
            model_name='historicaldesgloseservicio',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalestatusactividad',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfasesprocesos',
            name='cveproceso',
        ),
        migrations.RemoveField(
            model_name='historicalfasesprocesos',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfoto',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpersonaprincipal',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprocesos',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltipoactividad',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltipoevento',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltipopersona',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltiposervicio',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalClasifServicio',
        ),
        migrations.DeleteModel(
            name='HistoricalDesgloseServicio',
        ),
        migrations.DeleteModel(
            name='HistoricalEstatusActividad',
        ),
        migrations.DeleteModel(
            name='HistoricalFasesProcesos',
        ),
        migrations.DeleteModel(
            name='HistoricalFoto',
        ),
        migrations.DeleteModel(
            name='HistoricalPersonaPrincipal',
        ),
        migrations.DeleteModel(
            name='HistoricalProcesos',
        ),
        migrations.DeleteModel(
            name='HistoricalTipoActividad',
        ),
        migrations.DeleteModel(
            name='HistoricalTipoEvento',
        ),
        migrations.DeleteModel(
            name='HistoricalTipoPersona',
        ),
        migrations.DeleteModel(
            name='HistoricalTipoServicio',
        ),
    ]
