# Generated by Django 4.1.3 on 2023-01-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0008_remove_historicaldesgloseservicio_cveclasifservicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoactividad',
            old_name='id_PK',
            new_name='id_pk',
        ),
    ]
