# Generated by Django 4.1.3 on 2023-01-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0009_rename_id_pk_tipoactividad_id_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encevento',
            name='folioevento',
            field=models.SmallAutoField(db_column='FolioEvento', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalencevento',
            name='folioevento',
            field=models.IntegerField(blank=True, db_column='FolioEvento', db_index=True),
        ),
    ]
