# Generated by Django 4.1.3 on 2023-01-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0010_alter_encevento_folioevento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaprincipal',
            name='correo',
            field=models.EmailField(db_column='Correo', max_length=70),
        ),
    ]
