# Generated by Django 4.1.3 on 2023-01-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0011_alter_personaprincipal_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaprincipal',
            name='datestar',
            field=models.DateTimeField(auto_now_add=True, db_column='DateStar'),
        ),
    ]
