# Generated by Django 4.1.3 on 2023-01-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0013_alter_personaprincipal_cvetipopersona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoevento',
            name='descripcion',
            field=models.CharField(db_column='DescTipoEvento', max_length=60),
        ),
    ]
