# Generated by Django 4.1.3 on 2023-01-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0015_alter_encevento_opcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enceventoopcion',
            old_name='cveevento',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='enceventoopcion',
            old_name='cvepersona',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='historicalenceventoopcion',
            old_name='cveevento',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='historicalenceventoopcion',
            old_name='cvepersona',
            new_name='persona',
        ),
        migrations.RemoveField(
            model_name='fasesprocesos',
            name='cveproceso',
        ),
    ]
