# Generated by Django 4.1.3 on 2023-02-07 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0001_squashed_0017_detevento_tiempo_historicaldetevento_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detevento',
            name='estatus',
            field=models.ForeignKey(db_column='CveEstatus', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salones.estatusactividad'),
        ),
        migrations.AddField(
            model_name='detevento',
            name='nota',
            field=models.CharField(db_column='Notas', default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaldetevento',
            name='estatus',
            field=models.ForeignKey(blank=True, db_column='CveEstatus', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='salones.estatusactividad'),
        ),
        migrations.AddField(
            model_name='historicaldetevento',
            name='nota',
            field=models.CharField(db_column='Notas', default=None, max_length=100, null=True),
        ),
    ]
